#!/bin/bash

options="\
    --default-permissions\
    --read-only\
    --max-read-ahead 16M\
    --vfs-cache-mode full\
    --vfs-cache-max-age 10000h\
    --dir-cache-time 1000h\
    "

if test "$1" = "cloud"
then
    rclone mount drive-v1: /media/cloud/ --exclude "enc/" $options ${@:2}
fi

if test "$1" = "enc"
then
    rclone mount drive-v1-enc: /media/enc/ $options ${@:2}
fi
