#! /bin/sh

sxhkd -c ~/.config/bspwm/sxhkdrc &
xwallpaper --zoom ~/.config/wall.png
polybar example &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		2
bspc config window_gap			12
bspc config top_padding			25
bspc config split_ratio			0.5
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config click_to_focus		true
bspc config focus_follows_pointer	false
bspc config remove_disabled_monitors	true

bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"

